# Generated by Django 4.0.1 on 2022-01-31 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_post_description_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.CharField(max_length=280, null=True),
        ),
    ]
