# Generated by Django 4.0.1 on 2022-01-31 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_post_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_description',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
